//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_WebServiceCalculator.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        lab_WebServiceCalculator.ServiceReference1.HelloWorldResponse HelloWorld(lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_WebServiceCalculator.ServiceReference1.HelloWorldResponse> HelloWorldAsync(lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        double Add(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AddAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtraction", ReplyAction="*")]
        double Subtraction(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtraction", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SubtractionAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        double Multiplication(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MultiplicationAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        double Division(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DivisionAsync(double number1, double number2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public lab_WebServiceCalculator.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(lab_WebServiceCalculator.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_WebServiceCalculator.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(lab_WebServiceCalculator.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : lab_WebServiceCalculator.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<lab_WebServiceCalculator.ServiceReference1.WebService1Soap>, lab_WebServiceCalculator.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_WebServiceCalculator.ServiceReference1.HelloWorldResponse lab_WebServiceCalculator.ServiceReference1.WebService1Soap.HelloWorld(lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest inValue = new lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest();
            inValue.Body = new lab_WebServiceCalculator.ServiceReference1.HelloWorldRequestBody();
            lab_WebServiceCalculator.ServiceReference1.HelloWorldResponse retVal = ((lab_WebServiceCalculator.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_WebServiceCalculator.ServiceReference1.HelloWorldResponse> lab_WebServiceCalculator.ServiceReference1.WebService1Soap.HelloWorldAsync(lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_WebServiceCalculator.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest inValue = new lab_WebServiceCalculator.ServiceReference1.HelloWorldRequest();
            inValue.Body = new lab_WebServiceCalculator.ServiceReference1.HelloWorldRequestBody();
            return ((lab_WebServiceCalculator.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public double Add(double number1, double number2) {
            return base.Channel.Add(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double number1, double number2) {
            return base.Channel.AddAsync(number1, number2);
        }
        
        public double Subtraction(double number1, double number2) {
            return base.Channel.Subtraction(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractionAsync(double number1, double number2) {
            return base.Channel.SubtractionAsync(number1, number2);
        }
        
        public double Multiplication(double number1, double number2) {
            return base.Channel.Multiplication(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplicationAsync(double number1, double number2) {
            return base.Channel.MultiplicationAsync(number1, number2);
        }
        
        public double Division(double number1, double number2) {
            return base.Channel.Division(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> DivisionAsync(double number1, double number2) {
            return base.Channel.DivisionAsync(number1, number2);
        }
    }
}
